### ISSUE TITLE
[decouple] External Sites 1.4.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/external#12]
### Reason

- Decoupling release cycle from core so we can tag the app independently

### Tasks

- [x] add changelog
- [x] add Makefile

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [ ] Create "$version Testplan"

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries => https://github.com/owncloud/external/releases/tag/v1.4.0RC1
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable)

### Publishing

- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number: https://github.com/owncloud/external/pull/17

**Comment by PVince81** [comment]
1.4.0 RC1 needs smoke testing: https://github.com/owncloud/external/releases/tag/v1.4.0RC1

**Comment by PVince81** [comment]
stable10 branch is locked. we'll release from master.

note, there are some minor changes there, we should test that external sites actually still works

- [ ] TEST: external sites itself should still work
- [ ] TEST: external sites must work with theme-provided icons

**Comment by PVince81** [comment]
assigned @dpakach for manual regression testing

**Comment by patrickjahns** [comment]
While comparing a `stable10 core` with `stable10 apps` vs `master apps` noticed the following differences 

```
Files new/owncloud/apps/external/ajax/setsites.php and old/owncloud/apps/external/ajax/setsites.php differ
Files new/owncloud/apps/external/appinfo/info.xml and old/owncloud/apps/external/appinfo/info.xml differ
Files new/owncloud/apps/external/appinfo/signature.json and old/owncloud/apps/external/appinfo/signature.json differ
Files new/owncloud/apps/external/l10n/af_ZA.js and old/owncloud/apps/external/l10n/af_ZA.js differ
Files new/owncloud/apps/external/l10n/af_ZA.json and old/owncloud/apps/external/l10n/af_ZA.json differ
Files new/owncloud/apps/external/l10n/cs_CZ.js and old/owncloud/apps/external/l10n/cs_CZ.js differ
Files new/owncloud/apps/external/l10n/cs_CZ.json and old/owncloud/apps/external/l10n/cs_CZ.json differ
Files new/owncloud/apps/external/l10n/es_AR.js and old/owncloud/apps/external/l10n/es_AR.js differ
Files new/owncloud/apps/external/l10n/es_AR.json and old/owncloud/apps/external/l10n/es_AR.json differ
Files new/owncloud/apps/external/l10n/fa.js and old/owncloud/apps/external/l10n/fa.js differ
Files new/owncloud/apps/external/l10n/fa.json and old/owncloud/apps/external/l10n/fa.json differ
Files new/owncloud/apps/external/l10n/he.js and old/owncloud/apps/external/l10n/he.js differ
Files new/owncloud/apps/external/l10n/he.json and old/owncloud/apps/external/l10n/he.json differ
Files new/owncloud/apps/external/l10n/ka_GE.js and old/owncloud/apps/external/l10n/ka_GE.js differ
Files new/owncloud/apps/external/l10n/ka_GE.json and old/owncloud/apps/external/l10n/ka_GE.json differ
Files new/owncloud/apps/external/l10n/kn.js and old/owncloud/apps/external/l10n/kn.js differ
Files new/owncloud/apps/external/l10n/kn.json and old/owncloud/apps/external/l10n/kn.json differ
Files new/owncloud/apps/external/l10n/lt_LT.js and old/owncloud/apps/external/l10n/lt_LT.js differ
Files new/owncloud/apps/external/l10n/lt_LT.json and old/owncloud/apps/external/l10n/lt_LT.json differ
Files new/owncloud/apps/external/l10n/mk.js and old/owncloud/apps/external/l10n/mk.js differ
Files new/owncloud/apps/external/l10n/mk.json and old/owncloud/apps/external/l10n/mk.json differ
Files new/owncloud/apps/external/l10n/nn_NO.js and old/owncloud/apps/external/l10n/nn_NO.js differ
Files new/owncloud/apps/external/l10n/nn_NO.json and old/owncloud/apps/external/l10n/nn_NO.json differ
Files new/owncloud/apps/external/l10n/pl.js and old/owncloud/apps/external/l10n/pl.js differ
Files new/owncloud/apps/external/l10n/pl.json and old/owncloud/apps/external/l10n/pl.json differ
Files new/owncloud/apps/external/l10n/sk_SK.js and old/owncloud/apps/external/l10n/sk_SK.js differ
Files new/owncloud/apps/external/l10n/sk_SK.json and old/owncloud/apps/external/l10n/sk_SK.json differ
Files new/owncloud/apps/external/l10n/uk.js and old/owncloud/apps/external/l10n/uk.js differ
Files new/owncloud/apps/external/l10n/uk.json and old/owncloud/apps/external/l10n/uk.json differ
Files new/owncloud/apps/external/l10n/vi.js and old/owncloud/apps/external/l10n/vi.js differ
Files new/owncloud/apps/external/l10n/vi.json and old/owncloud/apps/external/l10n/vi.json differ
Files new/owncloud/apps/external/lib/external.php and old/owncloud/apps/external/lib/external.php differ
Files new/owncloud/apps/external/settings.php and old/owncloud/apps/external/settings.php differ
Files new/owncloud/apps/external/templates/settings.php and old/owncloud/apps/external/templates/settings.php differ
```

**Comment by patrickjahns** [comment]
Translation files and `signature.json` seems fine - we might need to doublecheck however the changes between the php files and `info.xml`

**Comment by PVince81** [comment]
- [x] find missing backports and refer in changelog for additional testing

**Comment by PVince81** [comment]
in the diff from the 10.1.1 version to the 1.4.0 RC1 version built above:

```
diff -r /home/vincent/temp/owncloud-10.1.1/apps/external/lib/external.php external/lib/external.php
29c29,31
<               if (($sites = json_decode(\OCP\Config::getAppValue("external", "sites", ''))) != null) {
---
>               $sites = \json_decode(\OC::$server->getConfig()
>                               ->getAppValue('external', 'sites', ''));
>               if ($sites !== null) {
Only in external: README.md
Only in /home/vincent/temp/owncloud-10.1.1/apps/external: settings.php
diff -r /home/vincent/temp/owncloud-10.1.1/apps/external/templates/settings.php external/templates/settings.php
34c34
<                       <img class="svg action delete_button" src="'.OCP\image_path("", "actions/delete.svg") .'" title="'.$l->t("Remove site").'" />
---
>                       <img class="svg action delete_button" src="' . image_path("", "actions/delete.svg") .'" title="'.$l->t("Remove site").'" />
47c47
<                       <img class="svg action delete_button" src="'.OCP\image_path("", "actions/delete.svg") .'" title="'.$l->t("Remove site").'" />
---
>                       <img class="svg action delete_button" src="'. image_path("", "actions/delete.svg") .'" title="'.$l->t("Remove site").'" />
```

changes look trivial, I think we can ignore. these will be covered by quick regression testing.

**Comment by dpakach** [comment]
@pvince81 1.4.0 RC1 Tarball is not working for me, Not sure why. When I check diff between the zip and tarball I get this.
```
➜ diff -bur external-1.4.0RC1\(tarball\)/external external-1.4.0RC1\(Zip\) 
Only in external-1.4.0RC1(Zip): ajax
Only in external-1.4.0RC1(tarball)/external/appinfo: signature.json
Only in external-1.4.0RC1(Zip): .gitignore
Only in external-1.4.0RC1(Zip): index.php
Only in external-1.4.0RC1(Zip)/l10n: .gitkeep
Only in external-1.4.0RC1(Zip)/l10n: .tx
Only in external-1.4.0RC1(Zip): LICENSE
Only in external-1.4.0RC1(Zip): Makefile
Only in external-1.4.0RC1(Zip): settings.php

```

**Comment by PVince81** [comment]
@dpakach thanks for the diff, indeed some files were missing.

I've added them now to the Makefile and created a RC2, please use it for testing: https://github.com/owncloud/external/releases/download/v1.4.0RC2/external-1.4.0RC2.tar.gz

**Comment by dpakach** [comment]
@PVince81  Ok thanks.

**Comment by dpakach** [comment]
External-1.4.0RC2 test plan
Test plan in QA repo - https://github.com/owncloud/QA/pull/617
Manual test issue - https://github.com/owncloud/external/issues/16

**Comment by dpakach** [comment]
Test plan is covered except for safari browser

**Comment by PVince81** [comment]
final release: https://github.com/owncloud/external/releases/tag/v1.4.0
